### PR TITLE
Added inventory-2-8 schema

### PR DESCRIPTION
**Pull request by jbrown-xentity**
Added inventory 2.8 schema. Should allow for new URL at inventory-2-8, and allow for testing in sandbox.

### CODE REVIEW

**Comment by adborden** [comment]
No explicit tests to add, but I would add the new `inventory-2-8` core to the [default](https://github.com/GSA/datagov-deploy-solr/blob/master/molecule/default/molecule.yml#L34) scenario just so that the new solr core is getting created within the existing test.

**Comment by adborden** [comment]
Part of https://github.com/gsa/datagov-deploy/issues/1481

**Review by mogul — CHANGES_REQUESTED** [review]
Aaron's feedback:
> No explicit tests to add, but I would add the new inventory-2-8 core to the default scenario just so that the new solr core is getting created within the existing test.

I want to see this too!

**Comment by jbrown-xentity** [comment]
Duplicate of #19, closing

**Pull request closed without merging**
